### ISSUE TITLE
Relationship fields returning null

### ISSUE THREAD

**Issue by dustyndoyle** [relate-app/gatsby-source-strapi#1]
First, thanks for creating this extension!

All the data is coming in great, the only issue I am having is relationship fields showing as null when I try to query them. I have a screenshot below of what I am seeing. Is there a specific naming convention this is looking for or is there something else I should be doing to get this? While doing this I also noticed the Internationalization field was returning null as well. Not sure if that is related or not.
![Screen Shot 2021-12-20 at 5 55 43 PM](https://user-images.githubusercontent.com/2131729/146843771-d2d87d4d-bfb1-48bb-88b4-b501c5c41e4f.png)

Thanks!

**Comment by timbrandin** [comment]
Have you added the Legal Page as a collection type included in config and enabled access to find on the public role? FYI will add api access support asap also

**Comment by dustyndoyle** [comment]
Yes, I believe I have all those things set. I can query the Legal Page collection separately it's just when trying to get it from a relationship field.
Also, API docs would be amazing. Thank you for all your work!

![Screen Shot 2021-12-21 at 8 12 43 AM](https://user-images.githubusercontent.com/2131729/146936376-cb90a7d4-6097-429e-85e1-d955009c79b8.png)
![Screen Shot 2021-12-21 at 8 14 39 AM](https://user-images.githubusercontent.com/2131729/146936377-c959c702-4d98-4f07-9bad-4571828adb0b.png)
![Screen Shot 2021-12-21 at 8 15 28 AM](https://user-images.githubusercontent.com/2131729/146936379-da0bc947-9dd7-4bac-9de8-e471d0b46214.png)

**Comment by timbrandin** [comment]
Maybe you can log in the resolver for the relationship type:
https://github.com/relate-app/gatsby-source-strapi/blob/master/build-types.js#L41

You can fork the repo and replace the source using `resolve: require('../gatsby-source-strapi')` in your gatsby-config.js

**Comment by timbrandin** [comment]
Oh wait, have you enabled find on the Site collection type?

**Comment by timbrandin** [comment]
Is it same for all types with relationships, just a though cause gatsby does also have a type name Site, maybe it is colliding with your type somehow. Otherwise are you up for a short meet, maybe we can figure it out together?

**Comment by timbrandin** [comment]
Any luck with this?

**Comment by timbrandin** [comment]
@dustyndoyle I figured it out, the relationships return null if they are one-to-many, this is fixed in `v4.2.0`

So I close this for now

**Comment by pepijn-vanvlaanderen** [comment]
Awesome work @timbrandin 🚀

**Comment by dustyndoyle** [comment]
Awesome job! I had to back off this project for more pressing things but this looks amazing.
