### ISSUE TITLE
Unexpected token M in JSON at position 0 

### ISSUE THREAD

**Issue by t-kietzmann** [relate-app/gatsby-source-strapi#11]
Related to: https://github.com/relate-app/gatsby-source-strapi/issues/5

I'm facing the same issue and have currently no idea how to solve it.
Simple Gatsby-Starter with Strapi 4.0.5 with one Collection Type:

API ID (Singular): job
API ID (Plural): jobs

Permissions: find and findOne

Api Token: Read-only

```
{
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: 'http://localhost:1337',
        collectionTypes: ['jobs'],
        locale: 'de', // default to all
        headers: {},
        token:
       '29ab2473e23a57dc3a42b56af422de14b7c95b94c31566345ddea34f695c6fc2885f02269962b9287f8457246820d00192c6c2574606c3debc97cfa3f827b6e05a5d17c18211f691ee26ca67d8e229478270d45021016d22e65847b0dea806f676da388fa0fd46b63267f492215238a2d58db8fe4585bce443c250d2bf96fedf',
      },
    },
```

**Comment by timbrandin** [comment]
First of all you need to use the Singular name of the Collection, this plugin uses the same name as presented visually in Strapi in the menu and adapts it to the naming convention in Strapi graphql.

**Comment by timbrandin** [comment]
I'm using version `4.3.4` and cannot reproduce the error, also if you're using a token you shouldn't need to set any permission.

**Comment by t-kietzmann** [comment]
Could solved with changing graphql packages in the strapi project (update from 4.0.0 and there was another graphql package).
Thanks!

**Comment by bigoper** [comment]
Hi @t-kietzmann 

Could you share your solution in detail? I'm facing the same issue here.
Thanks!
