### ISSUE TITLE
File System Route API return null

### ISSUE THREAD

**Issue by mariansimecek** [relate-app/gatsby-source-strapi#12]
Hi, 
I have a problem with gatsby and new File System Route API, it successfully generate pages by slug but graphql query output is null.

**File structure:** 
└── src
    ├── co-bylo
    │   ├── {StrapiAkce.slug}.tsx

**{StrapiAkce.slug}.tsx**
```jsx
import React from "react"
import { graphql } from "gatsby"
const CoByloPage = ({ data }: any) => {
  console.log(data)
  return <div></div>
}

export const query = graphql`
  query TestQuery($id: String) {
    strapiAkce(slug: { eq: $id }) {
      id
      eventName
      content
      slug
    }
  }

export default CoByloPage

```

**Console.log**
![image](https://user-images.githubusercontent.com/5357955/150984097-2fe258e3-6656-4111-b5ee-bb0f23df2653.png)

Thank you for great plugin.

**Comment by timbrandin** [comment]
I haven't checked out the new File System Route API, but do you get any data from the allStrapiAkce in the GraphQL explorer on http://localhost:8080/___graphql? And have you enabled preview on the plugin alternatively published the Akce document in Strapi?

**Comment by mariansimecek** [comment]
Yes I get data in GraphQL explorer and I have enabled preview.
I tried useStaticQuery and I see data: 
![image](https://user-images.githubusercontent.com/5357955/151139083-32fd58a8-8f80-46fc-8b4c-ca55abdf9246.png)

**Comment by mariansimecek** [comment]
I checked it and it works! Thank you for great work
