### ISSUE TITLE
Error: Unexpected token M in JSON at position 0

### ISSUE THREAD

**Issue by thomasuebi** [relate-app/gatsby-source-strapi#14]
Hi, first of all thank you for providing this plugin. Looking forward to use it.

While fetching data the following error occurred:

"@relate-app/gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Unexpected token M in JSON at position 0

I see this is an issue more people faced already. The answer provided there unfortunately did not work for me. Graphql package in strapi is up to date.
```
{
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337/api`,
        contentTypes: ["blog", "team", "partner"],
        singleTypes: [],
        // Only include specific locale.
        locale: "en", // default to all
        // Include drafts in build.
        preview: true, // defaults to false
        // Use application token.
        token: "xxx",
        // Add additional headers.
        headers: {},
      },
    },
```

The content types definitely exist like this in Strapi

If I change http://localhost:1337/api to http://localhost:1337 I receive
Response not successful: Received status code 401

All content types permission are activated find and findOne, including upload

**Comment by timbrandin** [comment]
Please check solution in https://github.com/relate-app/gatsby-source-strapi/issues/11
