### ISSUE TITLE
Limit on querying multiple media type

### ISSUE THREAD

**Issue by lorenciuse** [relate-app/gatsby-source-strapi#15]
In Strapi Graphql Playground I can limit the result for multiple media type by using limit on pagination argument.

![Screenshot (213)](https://user-images.githubusercontent.com/9565531/151468571-890c3259-9486-424a-8602-612f4e48fc0d.png)

But I can't do the same when querying in Gatsby Graphql as the field itself doesn't have an equal pagination argument like Strapi.

![Screenshot (214)](https://user-images.githubusercontent.com/9565531/151469111-909e8c64-78f7-4f4f-8a88-bd6bed1bfe60.png)

**Comment by timbrandin** [comment]
Alright, the plugin fetches up to 1000 entries from each relationship, I didn't see a need to add pagination to the relationship fields, feel free to write a PR for this feature.

Here is the current relationship implementation:
https://github.com/relate-app/gatsby-source-strapi/blob/master/build-types.js#L40-L59

**Comment by timbrandin** [comment]
Will close as there have been no further request for this.
