### ISSUE TITLE
name.replace is not a function when trying to build Gatsby

### ISSUE THREAD

**Issue by establishonline** [relate-app/gatsby-source-strapi#2]
I recently started working with Gatsby and Strapi (around the time when Strapi released v4) and I was stoked! That is, until everything started to break.

The original strapi-source-gatsby only works with v3 and some searching around led me to this plugin. Firstly, thanks a lot!

When I try to build the plugin after having installed this plugin, I get the following errors.
![gatsby-error-01](https://user-images.githubusercontent.com/67686616/147466533-ac7f5086-740e-4208-a732-588b9354893e.png)
![gatsby-error-02](https://user-images.githubusercontent.com/67686616/147466538-6a775539-e7e2-4c3c-97ef-bc5c9738ad76.png)

This is what my gatsby-config.js currently looks like.
```
require("dotenv").config({
	path: '.env',
});

module.exports = {
	siteMetadata: {
		siteUrl: "https://www.yourdomain.tld",
		title: "Site Name",
		description: "Site Description",
	},
	plugins: [
		"gatsby-plugin-sass",
		"gatsby-plugin-react-helmet",
		{
			resolve: 'gatsby-source-filesystem',
			options: {
				name: 'images',
				path: '${__dirname}/src/images',
			},
		},
		{
			resolve: 'gatsby-source-strapi',
			options: {
				apiURL: process.env.API_URL,
				collectionTypes: [{
          name: 'chapter',
          endpoint: "api/chapters"
        },
        {
          name: 'section',
          endpoint: "api/sections"
        }],
				singleTypes: [{
          name: 'homepage',
          endpoint: "api/homepage"
        },
        {
          name: 'global',
          endpoint: "api/global"
        }],
				queryLimit: 1000,
			},
		},
		"gatsby-plugin-image",
		"gatsby-transformer-sharp",
		"gatsby-plugin-sharp",
		{
			resolve: 'gatsby-plugin-manifest',
			options: {
				name: "gatsby-starter-default",
				short_name: "starter",
				start_url: "/",
				background_color: '#663399',
				theme_color: '#663399',
				display: 'minimal-ui',
				icon: 'src/images/icon.png',
			},
		},
		"gatsby-plugin-offline",
	],
};
```

I'm not entirely sure how to go about fixing this. My collections have components, which don't show up with the original gatsby-source-strapi. I was hoping this would fix that issue, no luck yet though.

**Comment by timbrandin** [comment]
Hello, this strapi plugin doesn't handle custom endpoints for the collection types, you only need to define the collections as they are written in Strapi aka with spaces etc, they will be transformed to the correct case and the plugin will find the field used for that collection type on the strapi graphql endpoint.

But for your sake I have also fixed so the collection formatting will not error and just ignore faulty input to the collectionTypes and singleTypes 👯
