### ISSUE TITLE
Response not successful: Received status code 400

### ISSUE THREAD

**Issue by geertvanleemputten** [relate-app/gatsby-source-strapi#20]
The same codebase locally is working, but my production environment is throwing this:

error "@relate-app/gatsby-source-strapi" threw an error while running the createSchemaCustomization lifecycle:

Response not successful: Received status code 400

  Error: Response not successful: Received status code 400

  - index.js:29 new ApolloError
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/errors/index.js:    29:28

  - QueryManager.js:611
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/core/QueryManage    r.js:611:19

  - asyncMap.js:16 both
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/utilities/observ    ables/asyncMap.js:16:53

  - asyncMap.js:9
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/utilities/observ    ables/asyncMap.js:9:72

  - new Promise

  - asyncMap.js:9 Object.then
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/utilities/observ    ables/asyncMap.js:9:24

  - asyncMap.js:17 Object.error
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/utilities/observ    ables/asyncMap.js:17:49

  - Observable.js:140 notifySubscription
    [commerce-frontend]/[zen-observable]/lib/Observable.js:140:18

  - Observable.js:179 onNotify
    [commerce-frontend]/[zen-observable]/lib/Observable.js:179:3

  - Observable.js:240 SubscriptionObserver.error
    [commerce-frontend]/[zen-observable]/lib/Observable.js:240:7

  - iteration.js:4
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/utilities/observ    ables/iteration.js:4:68

  - Array.forEach

  - iteration.js:4 iterateObserversSafely
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/utilities/observ    ables/iteration.js:4:25

  - Concast.js:36 Object.error
    [commerce-frontend]/[gatsby-source-strapi]/[@apollo]/client/utilities/observ    ables/Concast.js:36:21

  - Observable.js:140 notifySubscription
    [commerce-frontend]/[zen-observable]/lib/Observable.js:140:18

  - Observable.js:179 onNotify
    [commerce-frontend]/[zen-observable]/lib/Observable.js:179:3

**Comment by geertvanleemputten** [comment]
"GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production"

Now to figure out how to do that.

**Comment by geertvanleemputten** [comment]
introspection Boolean | If true, enables schema introspection by clients. This is required to use tools that figure out your server's schema from talking to it directly, like Apollo Sandbox and GraphQL Playground. (It's not needed for the non-Sandbox version of Apollo Studio Explorer, which uses the schema published in the Studio schema registry instead.)**The default value is true, unless the NODE_ENV environment variable is set to production.**
-- | --



</body>
</html>[introspection](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#introspection)
Boolean

If true, enables [schema introspection](https://graphql.org/learn/introspection/) by clients. This is required to use tools that figure out your server's schema from talking to it directly, like Apollo Sandbox and GraphQL Playground. (It's not needed for the non-Sandbox version of Apollo Studio Explorer, which uses the schema published in the Studio schema registry instead.)

The default value is true, unless the NODE_ENV environment variable is set to production.

**Comment by geertvanleemputten** [comment]
I renamed my NODE_ENV 'production' to 'prod' and now it's working.

So nobody is using this in production yet, im assuming?

**Comment by pepijn-vanvlaanderen** [comment]
This is mentioned in the readme: https://github.com/relate-app/gatsby-source-strapi#production-requirements
