### ISSUE TITLE
UploadFileQuery failed – Cannot return null for non-nullable field UploadFile.provider

### ISSUE THREAD

**Issue by LouisVallaey** [relate-app/gatsby-source-strapi#22]
Hello, seems that i get an error when trying to run gatsby with gatsby-source-strapi : 

success compile gatsby files - 0.461s
success load gatsby config - 0.013s
success load plugins - 0.499s
success onPreInit - 0.004s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
success initialize cache - 0.186s
success copy gatsby files - 0.062s
success Compiling Gatsby Functions - 0.139s
success onPreBootstrap - 0.146s
success createSchemaCustomization - 0.204s

 ERROR 

UploadFileQuery failed – Cannot return null for non-nullable field UploadFile.provider.

===== QUERY =====
query UploadFileQuery($pagination: PaginationArg, $updatedAt: DateTime) {
  uploadFiles(pagination: $pagination, filters: {updatedAt: {gt: $updatedAt}}) {
    __typename
    data {
      __typename
      id
      attributes {
        __typename
        name
        alternativeText
        caption
        width
        height
        formats
        hash
        ext
        mime
        size
        url
        previewUrl
        provider
        provider_metadata
        createdAt
        updatedAt
      }
    }
    meta {
      pagination {
        total
      }
    }
  }
}
===== VARIABLES =====
{
  "pagination": {
    "start": 0,
    "limit": 1000
  },
  "updatedAt": "1990-01-01T00:00:00.000Z"
}
===== ERROR =====
 Cannot return null for non-nullable field UploadFile.provider.

  Error: Cannot return null for non-nullable field UploadFile.provider.

i'm using strapi v 4.0.7 and gatsby 4.9.0

**Comment by Florian86** [comment]
I got the same error message using Gatsby v4.9.3 and strapi v4.1.3. The reason was an uploaded `favicon.ico` file. I also tried a different `favicon.ico` with the same result.
Deleting the file from strapi's media library "fixed" the problem.
