### ISSUE TITLE
All strapi nodes data remain the same on /__refresh

### ISSUE THREAD

**Issue by lorenciuse** [relate-app/gatsby-source-strapi#3]
I'm new into Gatsby and Strapi ecosystem. First of all, thank you for creating this plugin, since Strapi v4 has been out for a while, and there are compatibility issue for plugins including gatsby-source-strapi, your plugin indeed help a lot and the data is coming great, the only issue is when Strapi triggering a webhook on localhost:8000/__refresh, all the Strapi nodes data in Graphql aren't getting updated.

![Strapi Webhook](https://user-images.githubusercontent.com/9565531/147936792-2bd6296c-e4ed-4ec2-868c-bbf1b00f5645.PNG)

Above is a webhook settings for refreshing Gatsby without doing yarn develop

![Doesn't refreshed on relate-app gatsby-source-strapi](https://user-images.githubusercontent.com/9565531/147935543-c49d40f6-70db-4421-b6a3-65a8aca3eadb.PNG)

Meanwhile when using gatsby-source-strapi@1.0.2, after triggering a webhook, it does updated all the Strapi nodes data.

![Refreshed on gatsby-source-strapi 1 0 2](https://user-images.githubusercontent.com/9565531/147935979-08544d8c-be65-402b-8cb1-239b13e55774.PNG)

Is there any specific config to make that happen when using this plugin?

Thanks

**Comment by timbrandin** [comment]
Ah I see, I can repro locally, looking into it!

**Comment by timbrandin** [comment]
Ok I have fixed it in `v4.1.0`, forgot that apollo client by default caches all queries. Have also added support for using the api token if you're into that ;)

**Comment by lorenciuse** [comment]
Ah thank you! It's working as expected.

> Ok I have fixed it in `v4.1.0`, forgot that apollo client by default caches all queries. Have also added support for using the api token if you're into that ;)
